`Removes all the options that have been parsed by getopts from the parameters list, and so after that point, $1 will refer to the first non-option argument passed to the script`

diff --git a/dmenu/redyt b/dmenu/redyt
--- a/dmenu/redyt
+++ b/dmenu/redyt
@@ -5,8 +5,8 @@
 #[ ! "$(which "$prog")" ] && echo "Please install $prog!" && exit 1
 #done
 # If notify-send is not installed, use echo as notifier
-[ ! "$(which notify-send)" ] && notifier="echo" || notifier="notify-send"
-#notifier="notify-send"
+#[ ! "$(which notify-send)" ] && notifier="echo" || notifier="notify-send"
+notifier="notify-send"
 
 # reddit colors (dmenu flags only)
 colors="-nb #FF5700 -nf #CEE3F8 -sb #FF8b60 -sf #FF4500"
@@ -23,18 +23,19 @@ cachedir="/tmp/redyt"
 
 help_opt() {
 	#Check if necessary programs are installed
-	for prog in dmenu jq sxiv; do
-	[ ! "$(which "$prog")" ] && echo "Please install $prog!"
-	# How to not get which output
+	for Dep in dmenu jq; do
+		if ! command -v "$Dep" 1>/dev/null; then
+			printf "%s not found. Please install it.\n\n" "$Dep"
+		fi
 	done
 	printf "Usage:\n"
 	printf "\tredyt				asks for input in stdin using fzf\n"
-	printf "\tredyt <search query>		takes input from the passed query using fzf\n"
+	printf "\tredyt <subreddit>		takes input from the passed query using fzf\n"
 	printf "\tredyt -o			Displays the posts (usefull if you don't want to download everthing)\n"
 	printf "\tredyt -r			takes input and prompts using dmenu/rofi\n"
 }
 
-while getopts ":h :r o" opt; do
+while getopts ":h :r :o" opt; do
     case $opt in
 	h)
 	help_opt && exit 1	;;
@@ -42,13 +43,15 @@ while getopts ":h :r o" opt; do
 	#subreddit=$(echo | dmenu -p "🔎 Search: ")
 	subreddit=$(dmenu $colors -p "Select Subreddit r/" -i -l 10 < "$configdir/subreddit.txt" | cut -d\| -f1 | awk '{$1=$1;print}')
 	#promptcmd="$guicmd -p Video:"
-	[ -z "$query" ] && exit 1	;;
+	[ -z "$subreddit" ] && exit 1	;;
 	o)
 	format_reddit=1 ;;
 	?)
 	echo "Error! Invalid option!" && help_opt && exit 1	;;
     esac
 done
+# Removes all the options that have been parsed by getopts from the parameters list, and so after that point, $1 will refer to the first non-option argument passed to the script.
+shift "$((OPTIND-1))"
 
 # If no argument is passed
 [ -z "$subreddit" ] && if [ -z "$*" ]; then
@@ -71,45 +74,49 @@ $notifier "Redyt" "📩 Downloading your 🤡Memes\n⏳Queuing..."
 # first 100 entries (limit), and store it inside
 # cachedir/tmp.json
 limit=100
-tmp_json="$subreddit".json
+#tmp_json="$subreddit".json
 user_agent="User-Agent: your bot 0.1"
 #curl -sH "User-agent: 'your bot 0.1'" "https://www.reddit.com/r/$subreddit/hot.json?limit=$limit" \
-curl -s -G "https://www.reddit.com/r/$subreddit/$sortby.json" -d raw_json=1 -d limit="${limit}" -H "$user_agent" \
-	> "$cachedir"/"$tmp_json"
+#live_dl=$(curl -s -G "https://www.reddit.com/r/$subreddit/$sortby.json" -d raw_json=1 -d limit="${limit}" -H "$user_agent")
+	#> "$cachedir"/"$tmp_json"
 
 
 # Headers '-o' flag
 #format_reddit_json () {
+gap="                                                            "
 if [ $format_reddit ]; then
-	{	jq -r '.data.children[].data | [
+	curl -s -G "https://www.reddit.com/r/$subreddit/$sortby.json" -d raw_json=1 -d limit="${limit}" -H "$user_agent" | { jq -r '.data.children[].data | [
 				.title,
 				.preview.reddit_video_preview.fallback_url,
 				.url_overridden_by_dest
-			] | @tsv' < "$cachedir"/"$tmp_json"
+			] | @tsv'
 		#<<-EOF
 		#$*
 		#EOF
-	#	[ $? -eq 0 ] || exit 1
+		#[ $? -eq 0 ] || exit 1
 	} |
-	while IFS=$tab_space read title url _;do
+	while IFS=\t read title url _;do
 		[ -z "$url" ] && continue
 		printf "%s%s\t%s\n" "$title" "$gap$gap$gap" "$url"
-	done > "$cachedir"/posts_.TXT
-#}
-else
-# Create a list of images
-imgs=$(jq '.' < "$cachedir"/"$tmp_json" | grep url_overridden_by_dest | grep -Eo "http(s|)://.*(jpg|png|gif)\b" | sort -u)
+	done < "$cachedir"/posts_headers.TXT
 fi
+#}
+#else
+#í Create a list of images
+#imgs=$(jq -r '.' < "$live_dl" | grep url_overridden_by_dest | grep -Eo "http(s|)://.*(jpg|png|gif)\b" | sort -u)
+#fi
 
-media_urls=$(printf "%s" "$fields" | dmenu -l 15 | \
+#imgs=$(curl -s -G "https://www.reddit.com/r/$subreddit/$sortby.json" -d raw_json=1 -d limit="${limit}" -H "$user_agent" | jq -r '.data.children[].data | .url_overridden_by_dest' | sort -u)
+
+media_urls=$(dmenu $colors -p "Select Post" -i -l 10 < "$cachedir"/"post_headers.TXT"  | \
 	while IFS= read line; do
 		printf "%s " "${line##*$tab_space}"
-	done
-)
+	done)
+dmenurl $media_url
 [ -n "$media_urls" ] || exit 1
 
 # If there are no images, exit
-#[ -z "$imgs" ] && $notifier "Redyt" "sadly, there are no images for subreddit $subreddit, please try again later!😥" && exit 1
+[ -z "$imgs" ] && $notifier "Redyt" "sadly, there are no images for subreddit $subreddit, please try again later!😥" && exit 1
 
 # Download images to $cachedir (use task spooler)
 kill -37 "$(pidof dwmblocks)"	# task module bar
diff --git a/dmenu/termyt b/dmenu/termyt
--- a/dmenu/termyt
+++ b/dmenu/termyt
@@ -35,6 +35,7 @@ while getopts ":h :g :r :R" opt; do
 	#notifier=notify-send	;;
 	R)
 	status001=1
+	[ "$OPTARG" = " " ] && help_opt && exit 1
 	[ "$OPTARG" = "max" ] && res="maxresdefault.jpg"
 	[ "$OPTARG" = "hq"  ] && res="hqdefault.jpg"
 	[ "$OPTARG" = "mid" ] && res="mqdefault.jpg"
@@ -48,6 +49,8 @@ while getopts ":h :g :r :R" opt; do
 	#query="$*"	;;
     esac
 done
+# Removes all the options that have been parsed by getopts from the parameters list, and so after that point, $1 will refer to the first non-option argument passed to the script.
+shift "$((OPTIND-1))"
 
 [ -z "$query" ] && if [ -z "$*" ]; then
 	printf '%s' " Search: "
@@ -67,11 +70,19 @@ query=$(echo "$query" | sed \
 	-e 's| |+|g')
 [ -z "$query" ] && exit
 
+#fetching () { Function?
+# fetch the results with the $query and
+# delete all escaped characters
+
 # Why you wanna tell google you use linux?
 response="$(curl "https://www.youtube.com/results" -s -G --user-agent "$user_agent" --data-urlencode "search_query=$query" -H 'authority: www.youtube.com' -H 'accept-language: en-US,en;q=0.9' -L --compressed)"
+#response=$(curl -Gs --compressed "https://www.youtube.com/results?search_query=$query" --user-agent "$user_agent" | sed 's|\\.||g')
+#response="$(curl -s "https://www.youtube.com/results?search_query=$query" | sed 's|\\.||g')"
 
 # if unable to fetch the youtube results page, inform and exit (posix?)
+#if ! printf '%s' "$response" | grep -q "script" ; then echo "unable to fetch yt"; exit 1; fi
 [ -z "$response" ] && print_error "\033[31mERROR[#02]: Couldn't find data on site.\033[0m\n" && exit 1
+#if ! grep -q "script" <<< "$response"; then echo "unable to fetch yt"; exit 1; fi
 
 # regex expression to match video and playlist entries from yt result page
 vgrep='"videoRenderer":{"videoId":"\K.{11}".+?"text":".+?[^\\](?=")'
@@ -86,11 +97,9 @@ getresults() {
 # get the list of videos/playlists and their ids in videoids and playlistids
 videoids=$(getresults "$vgrep")
 playlistids=$(getresults "$pgrep" "(playlist)")
-
 # if there are playlists or videos, append them to list
 [ -n "$playlistids" ] && ids="$playlistids\n"
 [ -n "$videoids" ] && ids="$ids$videoids"
-
 # url prefix for videos and playlists
 videolink="https://youtu.be/"
 playlink="https://youtube.com/playlist?list="
@@ -98,19 +107,33 @@ playlink="https://youtube.com/playlist?list="
 # OPTIONAL: Display thumbnail on sxiv
 [ ! -d "$cachedir" ] && mkdir -p "$cachedir"
 img="http://img.youtube.com/vi"
+
+#max="maxresdefault.jpg"
+#HQ="hqdefault.jpg"
+#mid="mqdefault.jpg"
+#low="sddefault.jpg"
+
 # only one thumbnail, the selected one, before watching the video was the first use of this
-thumb() {
-	curl -sL "$img/$id/$res" > "$cachedir/$(echo "$choice").jpg" && sxiv -abp -s f "$cachedir/$(echo "$choice").jpg"  >/dev/null 2>&1 && rm "${cachedir:?}"/* ; echo "$ids" > ~/yt
-	}
+#thumb() {
+	#curl -sL "$img/$id/$res" > "$cachedir/$(echo "$choice").jpg" && sxiv -abp -s f "$cachedir/$(echo "$choice").jpg"  >/dev/null 2>&1 && rm "${cachedir:?}"/* ; echo "$ids" > ~/yt
+	#}
+
 # 30 thumbnails
 thumball() {
 	echo "$ids" | awk '{print $1}' | sed "s,^,&$img/,;s,$,&/$res," > "$cachedir"/thumb.txt
 	while read -r URL; do
 		var=$((var + 1))
-	$task -nf curl -L "$URL" > "$cachedir"/"$(echo -e "$ids" | sed "${var}q;d" | cut -d'	' -f2 | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr ' ' '_' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g").jpg";
+	$task -nf curl -L "$URL" > "$cachedir"/"$(printf '%s' "$ids" | sed "${var}q;d" | cut -d'	' -f2 | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr ' ' '_' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g").jpg";
 	done < $cachedir/thumb.txt
 	notify-send "Finished⌛" && sxiv -bpt -s f $cachedir/* ; rm "${cachedir:?}"/*
 }
+
+#		curl -sL "$URL" > "$cachedir/$(echo "$ids" | sed "${var}q;d" | awk '{print $1}').jpg";
+# The only problem here is that images don't appear in the "algorithm" order but does it really matter?
+#		curl -sL "$URL" > "$cachedir/$(echo -e "$ids" | tac | sed "${var}q;d" | cut -d'	' -f2).jpg";
+
+# prompt the results to user infinitely until they exit (escape)
+# while true; do # I don't need to search infinitely
 
 # Making this a function because I will be repeating this
 choose() {
@@ -120,8 +143,17 @@ choose() {
 	#if [ -z "$choice" ]; then exit; fi	# if esc-ed then exit
 	[ -z "$choice" ] && exit 		# if esc-ed then exit
 	id=$(printf '%s' "$ids" | grep -Fwm1 "$choice" | cut -d'	' -f1) # get id of choice
-	echo -e "$choice\t($id)"
+	printf '%s' "$choice\t($id)"
 }
+
+#choose_sxiv() {
+##	choice=$(echo -e "$ids" | cut -d'	' -f2 | $promptcmd) # dont show id
+#	#if [ -z "$choice" ]; then exit; fi	# if esc-ed then exit
+#	choice=$(sxiv -bpt -s f "$cachedir"/*)
+#	[ -z "$choice" ] && exit 		# if esc-ed then exit
+#	id=$(echo -e "$ids" | grep -Fwm1 "$choice" | cut -d'	' -f1) # get id of choice
+#	rm $cachedir/*
+#}
 
 #[ -n $description ] && youtube-dl "https://www.youtube.com/results?search_query=$query" --get-description >> "$cachedir"/description.TXT && setsid -f "$TERMINAL" -e less "$cachedir"/description.TXT
 [ -z "$status001" ] && choose
@@ -131,9 +163,9 @@ case $id in
 # the 'choice' variable as a second argument is to display it on a notification with dmenurl
 		# 11 digit id = video
 	???????????) dmenurl "$videolink$id" "$(echo "$choice" | sed 's/ *//')" ;;
-	#???????????) mpv "$videolink$id" ;;
+	#???????????) dmenurl "$videolink$id" "${choice// */}" ;;
 		# 34 digit id = playlist
 	??????????????????????????????????) dmenurl "$playlink$id" "$(echo "$choice" | sed 's/ *//')" ;;
-	#??????????????????????????????????) mpv "$playlink$id"	;;
+	#??????????????????????????????????) dmenurl "$playlink$id" "${choice// *//}" ;;
 		*) exit ;;
 esac
